### ISSUE TITLE
Issue: verify-exe.js throws error when root folder has spaces in name 

### ISSUE THREAD

**Issue by RyhilaEbrahim** [fluffynuts/gulp-tasks#10]
![image](https://user-images.githubusercontent.com/16575536/28466741-ae526ba0-6e2d-11e7-8aa9-b10ad1190cbd.png)

**Comment by fluffynuts** [comment]
I *think* this is _finally_ fixed with the last commit -- I have a project I've tested it on. Let me know if you see this again. Sorry this took so long -- it was easy to just work around, but the newer Jenkins uses the project name as the workspace folder name (with no option to change that I can find) so it's more pressing now (:
