### ISSUE TITLE
nuget downloading twice

### ISSUE THREAD

**Issue by kevinbosman** [fluffynuts/gulp-tasks#11]
If you start with a clean slate, add only an overridden `install-tools` with a simple dependency on `default-tools-installer`, then 2 copies of `nuget.exe` get downloaded simultaneously.
One by `get-local-nuget` and another by `default-tools-installer`.

**Comment by fluffynuts** [comment]
Yeah, I'm aware of this. It's because `get-local-nuget` is kicked off by `nuget-restore`, a dependency of `build`. `install-tools` is also marked as a dependency of `build` but I wasn't happy about trying to make it depend on `get-local-nuget`, since, for example, one may use tools provided by nuget in a project not using nuget for packages (think: karma, cobertura, report-generator for a ts/js project).

This is something which needs to be looked at -- I just haven't done so yet, taking the hit of two nuget.exe downloads instead :/

**Comment by fluffynuts** [comment]
this should be resolved by [https://github.com/fluffynuts/gulp-tasks/commit/ac9a71d74e164c4de178653960e7c390693e167b](https://github.com/fluffynuts/gulp-tasks/commit/ac9a71d74e164c4de178653960e7c390693e167b)

In addition, nuget downloading should be a lot more fault-tolerant and there's a promisify utility module for converting stuff like streams (or plaing-old-functions) to promises to make task composition a little easier

**Comment by kevinbosman** [comment]
I'm afraid it's actually still downloading nuget twice, just not at the same time any more. It's still downloading it again at the beginning of the `nuget-restore` task.

**Comment by fluffynuts** [comment]
Yeah, I saw this in PB the other night. Should now be resolved with https://github.com/fluffynuts/gulp-tasks/commit/05b1d44b75f4b0969c47708f73c8ccef32d390c4
