### ISSUE TITLE
Need a way to override default NUnit params during coverage

### ISSUE THREAD

**Issue by kevinbosman** [fluffynuts/gulp-tasks#12]
`gulp-dotnetcover.js` hardcodes several NUnit command line parameters.
There is a mechanism available to *add* parameters, with an overridable default of `"/framework:net-4.5 /labels"`
However, there are a couple of other NUnit parameters which are hardcoded and not overridable, eg. `--result` and `--x86`
There are occasions (eg. when running coverage in a container with limited memory), when you might want to override those other defaults, or add an incompatible option.
For example: with limited memory, NUnit often fails with `Unable to acquire remote process agent` due to excessive mem swapping. To resolve this it helps to add the `--inprocess` flag, which is incompatible with `--x86`.
So it would be helpful to be able to *remove* the `--x86` flag in this case. There just so happens to not be a `--x64` flag - thus the absence of `--x86` implies x64.

**Comment by fluffynuts** [comment]
the nunit options already have three ways to specify platform: "x86" (boolean) or "platform" or "architecture" (strings, which, when set to "x86", add the /x86 flag; when set to anything else (or if "x86" is false), you'll get no /x86 flag, which implies 64-bit (: -- which should solve the --inprocess issue?

I do remember, though, that you had a use-case for altering the result behavior (iirc, you wanted the logs to be split out because one monolithic logfile was causing issues)? Would it make sense to do as I already do for nunit labels, ie: when the runner finds "labels:" in the extra provides nunit options, it doesn't attempt to apply its own labels logic? IOW, suppress the result cli switch generation when they are already set in nunitOptions?

**Comment by kevinbosman** [comment]
You're absolutely right about the platform logic. Not sure how I missed that, considering that I submitted the PR which fixed that earlier this year 😊 

As for the result logic, I think what you're suggesting should work perfectly. Other use cases are outputting nunit3 xml files instead of the older nunit2 format (current default in gulp-dotnetcover.js), and converting the results via transform for better Jenkins reporting. (see https://github.com/nunit/nunit-transforms)

**Comment by fluffynuts** [comment]
Issue with overriding /result should be resolved with https://github.com/fluffynuts/gulp-tasks/commit/48ad8d8ccae54eac17d02c25c5cdacf15591043b

In addition, the following commit (https://github.com/fluffynuts/gulp-tasks/commit/fa2fadf33eba16da74f6b25210c2c09816eb38d4) addresses another issue we've seen: nunit agent madness.
This commit allows limiting the nunit agent count via
- the cover options, with the 'maxAgents' option
- an environment variable (NUNIT_MAX_AGENTS) -- which makes more sense, really, since it's set on the build host, not in the build job
- automatic selection of max agents based on the number of cores reported by Node's os.cpus() -- this limits the max agents to the number of available cores, which stopped the errors about not being able to get hold of nunit agents on my laptop (an i5, which is really only a dual-core with HT, so 4 reported cores, but the point is that coverage started working fine here, with that default option)
